# Usa la imagen oficial de PostgreSQL
FROM postgres:latest

# Establece las variables de entorno para la configuración de la base de datos
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
